function [fitresult, gof] = createFit(time, EtaHat)
%CREATEFIT(TIME,ETAHAT)
%  Create a fit.
%  
%  Data for 'ForceFit1' fit:
%      X Input : time
%      Y Output: EtaHat
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.
 
%  Auto-generated by MATLAB on 07-Dec-2012 17:45:31
 

%% Fit: 'ForceFit1'.
[xData, yData] = prepareCurveData( time, EtaHat );

% Set up fittype and options.
ft = fittype( 'sin1' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf];
opts.Robust = 'Bisquare';
opts.StartPoint = [0.981553250312771 0.628947478196155 -0.106855901161992];
opts.Upper = [Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'ForceFit1' );
h = plot( fitresult, xData, yData );
legend( h, 'EtaHat vs. time', 'ForceFit1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'time' );
ylabel( 'EtaHat' );
grid on


