% function H_tilde = H_tilde(theta,theta_dot,x,xdot,xs,y,ydot,ys,z,zdot,zs)
function H_tilde = Htilde_P(xs,ys,zs,theta,theta_dot,x,xdot,y,ydot,z,zdot)
%                            (Xsite,Ysite,Zsite,theta,theta_dot,x,xdot,y,ydot,z,zdot)
% %H_TILDE
%    H_TILDE = H_TILDE(THETA,THETA_DOT,X,XDOT,XS,Y,YDOT,YS,Z,ZDOT,ZS)

%    This function was generated by the Symbolic Math Toolbox version 5.9.
%    12-Nov-2012 13:44:52

t4 = cos(theta);
t5 = sin(theta);
t9 = t4.*ys;
t10 = t5.*xs;
t2 = t9+t10-y;
t3 = z-zs;
t7 = t4.*xs;
t8 = t5.*ys;
t6 = -t7+t8+x;
t11 = t2.^2;
t12 = t3.^2;
t13 = t6.^2;
t14 = t11+t12+t13;
t15 = 1.0./sqrt(t14);
t16 = t3.*t15;
t17 = t2.*t5;
t23 = t4.*t6;
t18 = t15.*(t17-t23);
t19 = t5.*t6;
t20 = t2.*t4;
t21 = t19+t20;
t22 = t15.*t21;
t24 = t4.*theta_dot.*ys;
t25 = t5.*theta_dot.*xs;
t26 = t24+t25+xdot;
t27 = t5.*theta_dot.*ys;
t30 = t4.*theta_dot.*xs;
t28 = t27-t30+ydot;
t29 = 1.0./t14.^(3.0./2.0);
t31 = t3.*zdot;
t32 = t6.*t26;
t34 = t2.*t28;
t33 = t31+t32-t34;
t35 = t6.*t15;
t36 = t15.*zdot;
t37 = z.*2.0;
t52 = zs.*2.0;
t38 = t37-t52;
t39 = t4.*t26;
t40 = t5.*t28;
t55 = t5.*t6.*theta_dot;
t56 = t2.*t4.*theta_dot;
t41 = t39+t40-t55-t56;
t42 = t2.*t5.*2.0;
t58 = t4.*t6.*2.0;
t43 = t42-t58;
t57 = t15.*t41;
t59 = t29.*t33.*t43.*(1.0./2.0);
t44 = -t57-t59;
t45 = t5.*t26;
t46 = t4.*t6.*theta_dot;
t60 = t4.*t28;
t61 = t2.*t5.*theta_dot;
t47 = t15.*(t45+t46-t60-t61);
t48 = t5.*t6.*2.0;
t49 = t2.*t4.*2.0;
t50 = t48+t49;
t62 = t29.*t33.*t50.*(1.0./2.0);
t51 = t47-t62;
t53 = t29.*t33.*t38.*(1.0./2.0);
t54 = -t36+t53;
H_tilde = reshape([t35,t15.*t26-t29.*t33.*(x.*2.0-t4.*xs.*2.0+t5.*ys.*2.0).*(1.0./2.0),-t2.*t15,t15.*t28+t29.*t33.*(y.*-2.0+t5.*xs.*2.0+t4.*ys.*2.0).*(1.0./2.0),t16,t36-t29.*t33.*t38.*(1.0./2.0),0.0,t35,0.0,-t2.*t15,0.0,t16,0.0,0.0,0.0,0.0,0.0,0.0,t18,t44,t22,t51,-t16,t54,t18,t44,t22,t51,-t16,t54,t18,t44,t22,t51,-t16,t54],[2, 18]);
% Adding to meet my shape reqs
H_tilde = H_tilde(:,1:12);