function Xprime = StateDeriv_WithPhi(time,X)
%
%Author: 
%           Zach Dischner
%Date:
%           10/18/2012
%Use: 
%           StateHistory=ode45(StateDeriv_WithPhi,[linspace(1,100),X_init)
% 
% Derivative function, designed to return the derivative of the Cartesian
%   R and V observations, incliuding the effect of the Earth's Oblateness
%   and drag. In addition, return the PHI matrix, reformed into a single
%   vector. 
%
% Written by Zach Dischner on 8/30/2012
%
% inputs:
%         time: time...
%         State  : A column vector. 18-state + PHI reformed
%                       X
%                       Y
%                       Z
%                       X'
%                       Y'
%                       Z'
%                       u_e
%                       J2
%                       Cd
%                       Xbar_sitei   (1 2 or 3) based on station coordinates
%                       Phi
%
%

%% Define Constants
% Oblateness
uE   = 3.986004415e14;                     % m^3/s^2
J2   = 1.082626925638815e-3;                % []
R_E  = 6378136.3;                           % m    Radius of earth

% Drag
Cd      = 2.0;
Area    = 3.0;                  % m^2
m       = 970;                  % kg
rho0    = 3.614e-13;            % kg/m^3
r0      = 700000.0 + R_E;       % m
H       = 88667.0;              % m
theta_dot  = 7.29211585530066e-5;  % rad/s




%% Form State Variables
Phi=reshape(X(19:end),sqrt(length(X(19:end))),sqrt(length(X(19:end))));
% Type this out for speed later
SatState = cell(18,1);
SatState=num2cell(X(1:18));
[x,y,z,xdot,ydot,zdot,na,na1,na2, ...
    Xsite1,Ysite1,Zsite1,Xsite2,Ysite2,Zsite2 ...
    Xsite3,Ysite3,Zsite3] = SatState{:};

r=sqrt(x^2 + y^2 + z^2);

%% Use Force Equations
F_U     = [...
              -uE/r^3*x*(1-3/2*J2*(R_E/r)^2*(5*(z/r)^2-1));
              -uE/r^3*y*(1-3/2*J2*(R_E/r)^2*(5*(z/r)^2-1));
              -uE/r^3*z*(1-3/2*J2*(R_E/r)^2*(5*(z/r)^2-3));
          ];
      
% [xdot ydot zdot] due to atmospheric drag
Va      = [
    xdot + theta_dot*y;
    ydot - theta_dot*x;
    zdot
    ];
va      = sqrt((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2);

rho_a   = rho0.*exp((r - r0)./H);

F_Drag = -0.5 .* Cd .* (Area./m) .* rho_a .* va .* Va;

% Assemble
F_a = F_U - F_Drag;

State_Deriv = [xdot ; ydot ; zdot ; F_a ; 0 ; 0 ; 0 ; 0 ; 0 ; 0 ; 0 ; 0 ; 0 ; 0 ; 0 ; 0]; % Add in station location with earth's rotation rate

% For now 
% A=load('A.mat');



%% Integrate Phi
A =...
[                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                          0,                                                                                                                                                                                                                  1,                                                                                                                                                                                                                  0,                                                                                                                                                                                                                0,                                                               0,                                                       0,                                                                                                                       0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                          0,                                                                                                                                                                                                                  0,                                                                                                                                                                                                                  1,                                                                                                                                                                                                                0,                                                               0,                                                       0,                                                                                                                       0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                          0,                                                                                                                                                                                                                  0,                                                                                                                                                                                                                  0,                                                                                                                                                                                                                1,                                                               0,                                                       0,                                                                                                                       0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
                                (uE*((3*J2*R_E^2*((5*z^2)/r^2 - 1))/(2*r^2) - 1))/(r^2)^(3/2) - (uE*x*((3*J2*R_E^2*x*((5*z^2)/r^2 - 1))/r^4 + (15*J2*R_E^2*x*z^2)/r^6))/(r^2)^(3/2) - (3*uE*x^2*((3*J2*R_E^2*((5*z^2)/r^2 - 1))/(2*r^2) - 1))/(r^2)^(5/2) - (Area*Cd*rho0*theta_dot*exp((r - r0)/H)*(xdot + theta_dot*y)*(ydot - theta_dot*x))/(2*m*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2)) + (Area*Cd*rho0*x*exp((r - r0)/H)*(xdot + theta_dot*y)*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2))/(2*H*m*(r^2)^(1/2)), (Area*Cd*rho0*theta_dot*exp((r - r0)/H)*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2))/(2*m) - (3*uE*x*y*((3*J2*R_E^2*((5*z^2)/r^2 - 1))/(2*r^2) - 1))/(r^2)^(5/2) - (uE*x*((3*J2*R_E^2*y*((5*z^2)/r^2 - 1))/r^4 + (15*J2*R_E^2*y*z^2)/r^6))/(r^2)^(3/2) + (Area*Cd*rho0*theta_dot*exp((r - r0)/H)*(xdot + theta_dot*y)^2)/(2*m*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2)) + (Area*Cd*rho0*y*exp((r - r0)/H)*(xdot + theta_dot*y)*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2))/(2*H*m*(r^2)^(1/2)), (z*(45*J2*m*uE*x*R_E^2*r^2 - 105*J2*m*uE*x*R_E^2*z^2 + 6*m*uE*x*r^4))/(2*m*(r^2)^(9/2)) + (z*(Area*Cd*r^8*rho0*xdot*exp((r - r0)/H)*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2) + Area*Cd*r^8*rho0*theta_dot*y*exp((r - r0)/H)*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2)))/(2*H*m*(r^2)^(9/2)), (Area*Cd*rho0*exp((r - r0)/H)*(theta_dot^2*x^2 + 2*theta_dot^2*y^2 - 2*theta_dot*x*ydot + 4*theta_dot*xdot*y + 2*xdot^2 + ydot^2 + zdot^2))/(2*m*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2)),                                                                    (Area*Cd*rho0*exp((r - r0)/H)*(xdot + theta_dot*y)*(ydot - theta_dot*x))/(2*m*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2)),                                                                                  (Area*Cd*rho0*zdot*exp((r - r0)/H)*(xdot + theta_dot*y))/(2*m*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2)), -(x*(3*J2*R_E^2*r^2 - 15*J2*R_E^2*z^2 + 2*r^4))/(2*(r^2)^(7/2)),     -(3*R_E^2*uE*x*(x^2 + y^2 - 4*z^2))/(2*(r^2)^(7/2)), (Area*rho0*exp((r - r0)/H)*(xdot + theta_dot*y)*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2))/(2*m), 0, 0, 0, 0, 0, 0, 0, 0, 0;
 (Area*Cd*rho0*x*exp((r - r0)/H)*(ydot - theta_dot*x)*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2))/(2*H*m*(r^2)^(1/2)) - (3*uE*x*y*((3*J2*R_E^2*((5*z^2)/r^2 - 1))/(2*r^2) - 1))/(r^2)^(5/2) - (Area*Cd*rho0*theta_dot*exp((r - r0)/H)*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2))/(2*m) - (Area*Cd*rho0*theta_dot*exp((r - r0)/H)*(ydot - theta_dot*x)^2)/(2*m*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2)) - (uE*y*((3*J2*R_E^2*x*((5*z^2)/r^2 - 1))/r^4 + (15*J2*R_E^2*x*z^2)/r^6))/(r^2)^(3/2),                                (uE*((3*J2*R_E^2*((5*z^2)/r^2 - 1))/(2*r^2) - 1))/(r^2)^(3/2) - (uE*y*((3*J2*R_E^2*y*((5*z^2)/r^2 - 1))/r^4 + (15*J2*R_E^2*y*z^2)/r^6))/(r^2)^(3/2) - (3*uE*y^2*((3*J2*R_E^2*((5*z^2)/r^2 - 1))/(2*r^2) - 1))/(r^2)^(5/2) + (Area*Cd*rho0*theta_dot*exp((r - r0)/H)*(xdot + theta_dot*y)*(ydot - theta_dot*x))/(2*m*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2)) + (Area*Cd*rho0*y*exp((r - r0)/H)*(ydot - theta_dot*x)*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2))/(2*H*m*(r^2)^(1/2)), (z*(45*J2*m*uE*y*R_E^2*r^2 - 105*J2*m*uE*y*R_E^2*z^2 + 6*m*uE*y*r^4))/(2*m*(r^2)^(9/2)) + (z*(Area*Cd*r^8*rho0*ydot*exp((r - r0)/H)*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2) - Area*Cd*r^8*rho0*theta_dot*x*exp((r - r0)/H)*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2)))/(2*H*m*(r^2)^(9/2)),                                                                    (Area*Cd*rho0*exp((r - r0)/H)*(xdot + theta_dot*y)*(ydot - theta_dot*x))/(2*m*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2)), (Area*Cd*rho0*exp((r - r0)/H)*(2*theta_dot^2*x^2 + theta_dot^2*y^2 - 4*theta_dot*x*ydot + 2*theta_dot*xdot*y + xdot^2 + 2*ydot^2 + zdot^2))/(2*m*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2)),                                                                                  (Area*Cd*rho0*zdot*exp((r - r0)/H)*(ydot - theta_dot*x))/(2*m*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2)), -(y*(3*J2*R_E^2*r^2 - 15*J2*R_E^2*z^2 + 2*r^4))/(2*(r^2)^(7/2)),     -(3*R_E^2*uE*y*(x^2 + y^2 - 4*z^2))/(2*(r^2)^(7/2)), (Area*rho0*exp((r - r0)/H)*(ydot - theta_dot*x)*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2))/(2*m), 0, 0, 0, 0, 0, 0, 0, 0, 0;
                                                                                                                                (Area*Cd*rho0*x*zdot*exp((r - r0)/H)*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2))/(2*H*m*(r^2)^(1/2)) - (3*uE*x*z*((3*J2*R_E^2*((5*z^2)/r^2 - 3))/(2*r^2) - 1))/(r^2)^(5/2) - (Area*Cd*rho0*theta_dot*zdot*exp((r - r0)/H)*(ydot - theta_dot*x))/(2*m*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2)) - (uE*z*((3*J2*R_E^2*x*((5*z^2)/r^2 - 3))/r^4 + (15*J2*R_E^2*x*z^2)/r^6))/(r^2)^(3/2),                                                                                                                                (Area*Cd*rho0*theta_dot*zdot*exp((r - r0)/H)*(xdot + theta_dot*y))/(2*m*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2)) - (3*uE*y*z*((3*J2*R_E^2*((5*z^2)/r^2 - 3))/(2*r^2) - 1))/(r^2)^(5/2) - (uE*z*((3*J2*R_E^2*y*((5*z^2)/r^2 - 3))/r^4 + (15*J2*R_E^2*y*z^2)/r^6))/(r^2)^(3/2) + (Area*Cd*rho0*y*zdot*exp((r - r0)/H)*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2))/(2*H*m*(r^2)^(1/2)),                                                                                  (Area*Cd*r^8*rho0*z*zdot*exp((r - r0)/H)*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2))/(2*H*m*(r^2)^(9/2)) - (9*J2*m*uE*R_E^2*r^4 - 90*J2*m*uE*R_E^2*r^2*z^2 + 105*J2*m*uE*R_E^2*z^4 + 2*m*uE*r^6 - 6*m*uE*r^4*z^2)/(2*m*(r^2)^(9/2)),                                                                                    (Area*Cd*rho0*zdot*exp((r - r0)/H)*(xdot + theta_dot*y))/(2*m*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2)),                                                                                    (Area*Cd*rho0*zdot*exp((r - r0)/H)*(ydot - theta_dot*x))/(2*m*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2)), (Area*Cd*rho0*exp((r - r0)/H)*(theta_dot^2*x^2 + theta_dot^2*y^2 - 2*theta_dot*x*ydot + 2*theta_dot*xdot*y + xdot^2 + ydot^2 + 2*zdot^2))/(2*m*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2)), -(z*(9*J2*R_E^2*r^2 - 15*J2*R_E^2*z^2 + 2*r^4))/(2*(r^2)^(7/2)), -(3*R_E^2*uE*z*(3*x^2 + 3*y^2 - 2*z^2))/(2*(r^2)^(7/2)),                 (Area*rho0*zdot*exp((r - r0)/H)*((xdot + theta_dot*y)^2 + (ydot - theta_dot*x)^2 + zdot^2)^(1/2))/(2*m), 0, 0, 0, 0, 0, 0, 0, 0, 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                          0,                                                                                                                                                                                                                  0,                                                                                                                                                                                                                  0,                                                                                                                                                                                                                0,                                                               0,                                                       0,                                                                                                                       0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                          0,                                                                                                                                                                                                                  0,                                                                                                                                                                                                                  0,                                                                                                                                                                                                                0,                                                               0,                                                       0,                                                                                                                       0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                          0,                                                                                                                                                                                                                  0,                                                                                                                                                                                                                  0,                                                                                                                                                                                                                0,                                                               0,                                                       0,                                                                                                                       0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                          0,                                                                                                                                                                                                                  0,                                                                                                                                                                                                                  0,                                                                                                                                                                                                                0,                                                               0,                                                       0,                                                                                                                       0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                          0,                                                                                                                                                                                                                  0,                                                                                                                                                                                                                  0,                                                                                                                                                                                                                0,                                                               0,                                                       0,                                                                                                                       0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                          0,                                                                                                                                                                                                                  0,                                                                                                                                                                                                                  0,                                                                                                                                                                                                                0,                                                               0,                                                       0,                                                                                                                       0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                          0,                                                                                                                                                                                                                  0,                                                                                                                                                                                                                  0,                                                                                                                                                                                                                0,                                                               0,                                                       0,                                                                                                                       0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                          0,                                                                                                                                                                                                                  0,                                                                                                                                                                                                                  0,                                                                                                                                                                                                                0,                                                               0,                                                       0,                                                                                                                       0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                          0,                                                                                                                                                                                                                  0,                                                                                                                                                                                                                  0,                                                                                                                                                                                                                0,                                                               0,                                                       0,                                                                                                                       0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                          0,                                                                                                                                                                                                                  0,                                                                                                                                                                                                                  0,                                                                                                                                                                                                                0,                                                               0,                                                       0,                                                                                                                       0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                          0,                                                                                                                                                                                                                  0,                                                                                                                                                                                                                  0,                                                                                                                                                                                                                0,                                                               0,                                                       0,                                                                                                                       0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                                                                                                                                          0,                                                                                                                                                                                                                  0,                                                                                                                                                                                                                  0,                                                                                                                                                                                                                0,                                                               0,                                                       0,                                                                                                                       0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
 


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             

bounds = length(Phi);
PhiPrime = A(1:bounds,1:bounds)*Phi;


%% Reform full state vector
Xprime = [State_Deriv ; reshape(PhiPrime,length(PhiPrime)^2,1)];











end











